"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const user_1 = require("../controllers/user");
const authenticate_1 = require("../middleware/authenticate");
const userRouter = (0, express_1.Router)();
userRouter.post('/signup', user_1.signup);
userRouter.post("/login", user_1.login);
userRouter.put("/update", authenticate_1.authenticate, user_1.updateUser);
userRouter.post("/purchase/:id", authenticate_1.authenticate, user_1.purchaseCourse);
exports.default = userRouter;
